# Generated by Django 4.0.4 on 2022-06-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'CourseTeacher'},
        ),
    ]
